server:
  port: 8080
  servlet:
    context-path: /bdss
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/BDSS"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: duic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "SWP391/HuynhChauDucVoa/gwhOpxfAHeMMGae/o3R1n44DPt8Qfzd2/HEm+fvRF"
  valid-duration: 24
  refreshable-duration: 48