server:
  port: 8080
  servlet:
    context-path: /bdss
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/BDSS"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: duic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ollamabakery@gmail.com #tạo biến môi trường để bảo mật
    password: frii snaa sgsa uasx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "SWP391/HuynhChauDucVoa/gwhOpxfAHeMMGae/o3R1n44DPt8Qfzd2/HEm+fvRF"
  valid-duration: 24
  refreshable-duration: 48
