server:
  port: 8080
  servlet:
    context-path: /bdss
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/BDSS"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: duic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true